### ISSUE TITLE
CoreGalleryBlock doesn't give all image attributes 

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-gql-gutenberg#13]
Ideally we get the full image mediaItem data (srcSet, sizes, ACF meta etc...) for the images in a gallery.

Perhpas like this?
```
    ... on CoreGalleryBlock {
     	name
      attributes {
        ... on CoreGalleryBlockAttributes {
          images {
               ... on MediaItem {
                   srcSet
                   sizes
                   alt
                   title
               }
          }
        }
      }
    }
```

But open to other ways to achieve this.

**Comment by rsm0128** [comment]
![image](https://user-images.githubusercontent.com/45686588/114948493-116d8e00-9e8a-11eb-9631-e87401895a7e.png)
@drewbaker I added `mediaItems` field to CoreGalleryBlock. One problem is media items are not sorted in the gallery order.

**Comment by rsm0128** [comment]
@drewbaker `mediaItems` are sorted in the correct order with the last commit. Please check.
