### ISSUE TITLE
BlockAttributes should return all attributes

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/wp-gql-gutenberg#17]
BlockAttributes is not returning all attributes set in blocks.

You can see in graphiQL that the title's textAlign is properly returning "center", but textColor is not "red".  (see attached images)

ideally all blocks would include these default attributes: 
```
     ... on BlockAttributes {
              content
              textAlign
              fontSize
              textColor
              className
              backgroundColor
            }
```

<img width="1264" alt="Screen Shot 2021-04-13 at 3 07 44 PM" src="https://user-images.githubusercontent.com/13562688/114627750-9da16a80-9c6a-11eb-9e25-c6a7a31bc111.png">
<img width="1241" alt="Screen Shot 2021-04-13 at 3 07 11 PM" src="https://user-images.githubusercontent.com/13562688/114627767-a3974b80-9c6a-11eb-87d2-81b9befe753d.png">

**Comment by rsm0128** [comment]
![image](https://user-images.githubusercontent.com/45686588/115064149-8d69e380-9f27-11eb-8933-48de8e18fdeb.png)
![image](https://user-images.githubusercontent.com/45686588/115064285-b8543780-9f27-11eb-871b-1cb21080396c.png)
As you can see in the screenshots, the `textColor`, `backgroundColor` works for the blocks including heading block.

But in your test case, the color is not applied to the heading. Instead it is applied to the child span. 
You can confirm it in `Code editor` view.
![image](https://user-images.githubusercontent.com/45686588/115065153-bfc81080-9f28-11eb-8e8b-1fc057265f6e.png)

In my example, the markup code is `<h2 class="has-text-align-center custom-class has-vivid-red-color has-pale-pink-background-color has-text-color has-background has-medium-font-size"><span>Ths is heading block</span>.</h2>`
As you can see all the classes appended to the h2 tag. But you should have color classes attached to the span in your markup.

**Comment by rsm0128** [comment]
Here is the better example.
1. Difference In Visual editor
![image](https://user-images.githubusercontent.com/45686588/115066076-fc483c00-9f29-11eb-952d-f6d3700a781f.png)
![image](https://user-images.githubusercontent.com/45686588/115066181-20a41880-9f2a-11eb-8b8e-c510419a137d.png)

2. Difference in Code editor
![image](https://user-images.githubusercontent.com/45686588/115066488-91e3cb80-9f2a-11eb-814e-85a44ea8d854.png)

3. Difference in WP-GraphQL
![image](https://user-images.githubusercontent.com/45686588/115066585-b770d500-9f2a-11eb-8eb6-0dfc66e72a9a.png)

**Comment by drewbaker** [comment]
I can confirm this not working correctly:

```html
<!-- wp:heading {"style":{"color":{"text":"#ef275c","background":"#0d0921"}}} -->
<h2 class="has-text-color has-background" style="background-color:#0d0921;color:#ef275c">Test heading</h2>
<!-- /wp:heading -->
```

```gql
query MyQuery {
  page(id: "example-page", idType: URI) {
    blocks {
      ... on CoreHeadingBlock {
        name
        attributes {
          ... on CoreHeadingBlockAttributes {
            fontSize
            backgroundColor
            textColor
          }
        }
      }
    }
  }
}
```
```json
  "data": {
    "page": {
      "blocks": [
        {},
        {
          "name": "core/heading",
          "attributes": {
            "fontSize": "",
            "backgroundColor": "",
            "textColor": ""
          }
        },
        {}
      ]
    }
  }
```

**Comment by rsm0128** [comment]
I can see it doesn't work with custom values. Let me handle the case.

**Comment by rsm0128** [comment]
@drewbaker @dChiamp I fixed it and pushed to dev branch. Please check and let me know opinion. Thanks

**Comment by dChiamp** [comment]
That update is working!

Is it possible for the preset color options to return a hex like the custom colors?
You can see the custom background color is a hex while the preset option returns the name string of the color:

<img width="1201" alt="Screen Shot 2021-04-19 at 10 26 15 AM" src="https://user-images.githubusercontent.com/13562688/115278015-cd80c000-a0f9-11eb-9804-7922e44265f7.png">
<img width="872" alt="Screen Shot 2021-04-19 at 10 26 01 AM" src="https://user-images.githubusercontent.com/13562688/115278028-d1144700-a0f9-11eb-9c20-b4221657c8d5.png">

**Comment by drewbaker** [comment]
Or better yet, textColor.name and textColor.code?

**Comment by rsm0128** [comment]
Please check the latest commit. I added `backgroundColorCode`, `textColorCode`, and `fontSizeValue` attribute

**Comment by rsm0128** [comment]
Yes, it supports all the blocks with backgroundColor, textColor and fontSize setting

**Comment by dChiamp** [comment]
awesome! tested and confirmed its working: 
![Uploading Screen Shot 2021-04-19 at 1.52.23 PM.png…]()
