### ISSUE TITLE
Latest fixes for mediaItems is breaking other queries

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/wp-gql-gutenberg#21]
I tested the gallery mediaItems query and its working, but it is breaking other page queries:
<img width="1025" alt="Screen Shot 2021-04-19 at 3 59 17 PM" src="https://user-images.githubusercontent.com/13562688/115313495-3aab4a00-a128-11eb-9bda-b710e9d6b71f.png">

<img width="904" alt="Screen Shot 2021-04-19 at 3 58 39 PM" src="https://user-images.githubusercontent.com/13562688/115313519-45fe7580-a128-11eb-9095-7bd1754d35f6.png">

**Comment by rsm0128** [comment]
Fixed. added type validation check to prevent the error.

**Comment by dChiamp** [comment]
fixed! thank you
