### ISSUE TITLE
Error querying for blocks on custom post types

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/wp-gql-gutenberg#25]
Getting this error when querying blocks on custom post types:

<img width="756" alt="cpt-block-err" src="https://user-images.githubusercontent.com/13562688/120711888-c5e06500-c474-11eb-8192-1ba55ce2c3dc.png">

The CPT is set to show in graphql. I can verify that's working bc I'm able to query for other acf fields.

**Comment by dChiamp** [comment]
I've also added these fields to the post registration arguments array: https://wordpress.stackexchange.com/questions/324221/enable-gutenberg-on-custom-post-type to no avail.

**Comment by drewbaker** [comment]
@rsm0128 can you take a look at this?

**Comment by rsm0128** [comment]
![image](https://user-images.githubusercontent.com/45686588/121447867-86b09780-c9d1-11eb-9472-20284e198774.png)
@drewbaker @dChiamp I tested block query on custom post type, but it works fine for me.
It would be great if you provide me access to the site, so that I can debug the issue on it.

**Comment by rsm0128** [comment]
@dChiamp Is this issue fixed or still waiting my response?

**Comment by dChiamp** [comment]
@rsm0128 it's still an issue, but I ended up not needing to query for blocks on CPTs in this project. i can slack you the login credentials to test. Thanks for following up

**Comment by rsm0128** [comment]
OK, please send me the credential. Thanks
