### ISSUE TITLE
"GraphQL Gutenberg" menu option not showing

### ISSUE THREAD

**Issue by austinblanchard** [funkhaus/wp-gql-gutenberg#31]
Latest version hides the option for GraphQL Gutenberg.

Can manually access it by going to `/wp-admin/admin.php?page=wp-graphql-gutenberg-admin`

**Comment by drewbaker** [comment]
Fixed with https://github.com/funkhaus/wp-gql-gutenberg/commit/c56f795867473d0866ada847939f0155d56c5b08
