### ISSUE TITLE
Update image block to return a single node (not nodes). Will then work better with new gallery block.

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-gql-gutenberg#33]
The new Gallery Block that WordPress released has changed the data structure. This is the new query:

```
    innerBlocks {
      name
      ... on CoreImageBlock {
        mediaItem {
          nodes {
            ...MediaImage
          }
        }
      }
    }
```

But it's weird that each image in the gallery returns an array of 1 image, `innerBlocks[0].mediaItem.nodes[0]` not sure it makes sense to have an array of nodes on this? 

Seems to me we should update the image the this to return a single node:
https://github.com/funkhaus/wp-gql-gutenberg/blob/main/src/Schema/Types/Connection/CoreImageBlockMediaItemConnection.php

And then we probably don't need this at all:
https://github.com/funkhaus/wp-gql-gutenberg/blob/main/src/Schema/Types/Connection/CoreGalleryBlockMediaItemsConnection.php

**Comment by drewbaker** [comment]
Maybe this comment from Slack helps:

> In case you're still wondering about this one you can set the connection to be a oneToOne connection. Here's the 2 spots where you need to do it:

![cleanshot_2022-04-04_at_22 13 11_2x](https://user-images.githubusercontent.com/475015/162363328-22a6f37a-0c60-4d9b-9777-ae5ce3b37290.png)

**Comment by rsm0128** [comment]
@drewbaker Yes, we can use oneToOne connection. One doubt is backward compatibility. If we update the `resolve` function for the `CoreImageBlockMediaItemConnection`, the old sites built with this will be broken. Choose another name mediaItemSingle maybe?

**Comment by rsm0128** [comment]
PR created to fix this problem. https://github.com/funkhaus/wp-gql-gutenberg/pull/42
