### ISSUE TITLE
Fatal error on fresh install -  conflict with Classic Editor plugin

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-gql-gutenberg#46]
On a fresh install, all latest versions, I can't get a "Update block registry" to succeed, and if I try going to GraphiQL I get this error:

Also, I noticed that the "GraphQL Gutenberg" menu item is no longer nested under GraphQL menu group like it used to be.

<img width="928" alt="Screenshot 2023-01-24 at 9 06 27 PM" src="https://user-images.githubusercontent.com/475015/214397268-9a68877b-d821-42ef-8445-cc986b70bfbd.png">
<img width="1150" alt="Screenshot 2023-01-24 at 9 05 49 PM" src="https://user-images.githubusercontent.com/475015/214397294-d7c37b3c-4bd8-4e86-afa5-c25384c347eb.png">
<img width="1508" alt="Screenshot 2023-01-24 at 9 05 58 PM" src="https://user-images.githubusercontent.com/475015/214397300-3918ce94-5a77-491e-933d-a1f4eb0649d9.png">

**Comment by drewbaker** [comment]
When trying the API directly: https://elizabeth-taylor-api.flywheelsites.com/index.php?graphql

<img width="1372" alt="Screenshot 2023-01-24 at 9 09 11 PM" src="https://user-images.githubusercontent.com/475015/214397768-283791f8-a4b9-4984-90a2-b5bc340057bb.png">

**Comment by drewbaker** [comment]
OK this seems to work if I disable the Classic Editor plugin... Which makes sense that you wouldn't be able to have both... But perhaps a better error/warning is in order?

**Comment by drewbaker** [comment]
Would still like to move the menu item back under the GraphQL one.

**Comment by rsm0128** [comment]
@drewbaker I pushed a commit to fix this issue. https://github.com/funkhaus/wp-gql-gutenberg/commit/8d64c8cc12066bbedacbd07105737a5d4e8f4066
