### ISSUE TITLE
Image blocks that use src hosted outside media library give server errors

### ISSUE THREAD

**Issue by drewbaker** [funkhaus/wp-gql-gutenberg#53]
It's possible to embed an image that is hosted off site, like so:

```
<!-- wp:image {"id":1202445916} -->
<figure class="wp-block-image"><img src="https://deadline.com/wp-content/uploads/2018/08/bwfuzzydoorlogo.jpg" alt="" class="wp-image-1202445916"/></figure>
<!-- /wp:image -->
```

When queried, the `mediaItem` resource will give a server error (see screen shot):

```
query NewsDetail($uri: String!) {
  nodeByUri(uri: $uri) {
    id
    ... on Post {
      blocks {
        name
        ... on CoreImageBlock {
          mediaItem {
            node {
              id
            }
          }
        }        
      }
    }
  }
}
```

The fact this doesn't work is not a surprise, there is no `mediaItem` in this case as the media item isn't in the WordPress database. So I suppose it should just return `null` in this case, or whatever is WP-GQL for empty...

![Screenshot 2023-04-12 at 4 13 06 PM](https://user-images.githubusercontent.com/475015/231605987-be453770-103f-41e1-b88a-9056d926593d.png)

**Comment by rsm0128** [comment]
@drewbaker I created a [PR](https://github.com/funkhaus/wp-gql-gutenberg/pull/54) to resolve this issue
