### ISSUE TITLE
Core fields query issue in WP V6.4.4 and higher [URGENT]

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/wp-gql-gutenberg#60]
These core fields for the following blocks are broken in wordpress Versions 6.4.4 and higher:

- field `text` on type `CoreButtonBlockAttributes`
- field `content` on type `CoreListItemBlockAttributes`
- field `citation` on type `CoreQuoteBlockAttributes`
- field `content` on type `CoreParagraphBlockAttributes`
- field `content` on type `CoreHeadingBlockAttributes`
- field `caption` on type `CoreGalleryBlockAttributes`
- field `caption` on type `CoreEmbedBlockAttributes`
- field `caption` on type `CoreImageBlockAttributes`
- field `content` on type `CoreParagraphBlockAttributes`

I've updated fuxt-backend to WordpPress version 6.5.2 to reproduce the error there so you can easily test. 
That causes the same error as v6.4.4.

Flywheel is auto updating a lot of our sites from WP v6.4.3 to v6.4.4 so this issue is having a big impact.

We've tried updating all plugins, adding the newest fuxt-backend theme, and updating to latest WP version without success.

Here's a screenshot of the error: 
<img width="1682" alt="gql-err" src="https://github.com/funkhaus/wp-gql-gutenberg/assets/13562688/72c9df4c-734c-4a52-970c-fef12e8c89c5">

**Comment by drewbaker** [comment]
I just updated all plugins and the theme on fuxt-backend, and it seems to be working... but doing the same on other client sites doesn't seem to work... so it's very confusing!

**Comment by drewbaker** [comment]
Seems to be related with the move from 6.4.3 to 6.4.4.

Something that changed here: https://core.trac.wordpress.org/ticket/59828

**Comment by drewbaker** [comment]
Maybe this? https://github.com/alleyinteractive/wp-graphql-gutenberg/commit/92e9640e301bc7831713bb9617e42ef31d55e80b

**Comment by drewbaker** [comment]
Temp solution is to just limit wordpress to version 6.4.3 until this is solved.

**Comment by austinblanchard** [comment]
fixed with https://github.com/funkhaus/wp-gql-gutenberg/pull/61
