### ISSUE TITLE
Conflict in 'content' attributes for String type in ParagraphBlock and HeadingBlock

### ISSUE THREAD

**Issue by dChiamp** [funkhaus/wp-gql-gutenberg#62]
Since the last plugin update some sites are returning an error for `content` field type `String` vs `String!` in `ParagraphBlock` and `HeadingBlock`:

<img width="1504" alt="graphql-err" src="https://github.com/funkhaus/wp-gql-gutenberg/assets/13562688/45d41589-3ff1-4d61-8d0f-8583ec4e8e39">

You can see this on the MakeMake WordPress backend in the graphIQL explorer here:
<img width="1690" alt="graphIQL-err" src="https://github.com/funkhaus/wp-gql-gutenberg/assets/13562688/77a2a804-b0dd-43c9-bfc9-2ce618fc6210">

I invited you to the MakeMake project so you can test.

My temporary workaround was to alias the `content` field with `text: content`, but this is not ideal since we need to then update the frontend component with the new field names.

**Comment by drewbaker** [comment]
We think it's because of the `value` and `values` type used on these blocks:

![Screen Shot 2024-04-21 at 4 47 19 PM](https://github.com/funkhaus/wp-gql-gutenberg/assets/475015/216b22a6-d3b4-422b-abbb-904c345661d4)
![Screen Shot 2024-04-21 at 4 48 12 PM](https://github.com/funkhaus/wp-gql-gutenberg/assets/475015/59cc2d68-8739-40ce-b6ee-9ab01beb2456)

**Comment by rsm0128** [comment]
@drewbaker @dChiamp I can't replicate the issue on my local and MakeMake as well. Could you provide me more context, please?

**Comment by drewbaker** [comment]
Pretty sure it has to do with values and value and aliasing it to content like we do. Because content normally a String! and values/value is a String.

**Comment by drewbaker** [comment]
Fixed with https://github.com/funkhaus/wp-gql-gutenberg/pull/63
